### PR TITLE
Convert warning to debug for common msg.

### PR DESCRIPTION
**Pull request by btimby**
Silence this message.

### CODE REVIEW

**Review by giampaolo — COMMENTED** [review]
Mmmm this was useful during testing (also for CI services). May I suggest the following change?

```
msg = "No handler for %r, defaulting to %r" % (mime, DEFAULT_MIME)
if "FULLTEXT_TESTING" in os.environ:
    LOGGER.warn(msg)
else:
    LOGGER.debug(msg)
```

FULLTEXT_TESTING env var is already set by `make test`.

**Review by tspelde — APPROVED** [review]
Tested and working

**Review by tspelde — APPROVED** [review]

**Review by giampaolo — APPROVED** [review]
LGTM

**Comment by tspelde** [comment]
@btimby Can we merge this in please?  I have tested it.

**Comment by btimby** [comment]
@tspelde Yeah, it had a merge conflict earlier today which I resolved but had not yet circled back to merge after CI triggered.

**Pull request merged**
