### PR TITLE
Add support for source code extensions

### LINKED ISSUE #65: Support source code files.
Map source code files to `__text` backend.

### PR DESCRIPTION
**Pull request by giampaolo**
Fixes #65.

### CODE REVIEW

**Comment by giampaolo** [comment]
> Is there any way to use SRC_CODE_EXTS with register_backend() rather than using a special case?

Mmmm I don't think so. Point is not all source code extensions have a corresponding mime type (probably very few actually), hence the special case.

**Comment by btimby** [comment]
Can we "invent" a mime type like `application/<extension>` for these?

**Comment by giampaolo** [comment]
How do you feel about `register_extension(ext, backend)`?

**Comment by giampaolo** [comment]
On a second thought `register_extension(ext, backend)` is probably overkill. I followed your original suggestion and used a custom mime name.

**Pull request merged**
